# Created with YamlCreate.ps1 v2.2.1 $debug=QUSU.CRLF.7-3-1.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: Logitech.GHUB
PackageVersion: 2023.2.3424
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
UpgradeBehavior: uninstallPrevious
Installers:
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://download01.logi.com/web/ftp/pub/techsupport/gaming/lghub_installer.exe
  InstallerSha256: 6FAD9C90CA4D032B6582008F0D48EF2145EE600FF9BED066ADAB9DBDB8466322
ManifestType: installer
ManifestVersion: 1.4.0
